# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WechatUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatarUrl', models.TextField()),
                ('city', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('gender', models.IntegerField()),
                ('language', models.CharField(max_length=20)),
                ('nickName', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=20)),
            ],
        ),
    ]
